server:
  port: 9190
spring:
  output:
    ansi:
      enabled: always
topic:
  name: tutorialspedia
request:
  endpoint:
    url:
      json-dummy-data: https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json

#: When lazy initialization is enabled, beans are created as they are needed rather than during application startup.
  main:
    lazy-initialization: true
#spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
